export const allrest = [
    {
        "address": "50741 Corporate Dr, Shelby Twp, MI 48315, USA",
        "capacity": 20,
        "city": "Shelby Twp",
        "description": "",
        "id": 1,
        "lat": 42.6680319,
        "lng": -83.0118459,
        "name": "Verona Inspired Italian",
        "num_of_reviews": 0,
        "phone_number": "(586) 473-0200",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj415wVlw08ApaJADv-jT-dOjKiShw3ogax4bTTYeMdjiZEQbo498EYpGP59PLuvyd1RU7njSGn3Hs9K9kDsSu_2M00ZwME5YeYI=s1600-w1000",
        "rating": 5,
        "type": "Italian"
    },
    {
        "address": "30 E Big Beaver Rd, Troy, MI 48083, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "With our thoughtfully chosen menu and locally sourced ingredients, Verona-Inspired Italian strives to deliver cuisine that is fresh and uncomplicated, yet unique and refined; honest and spirited food and drinks that our nearby neighbors and out of town guests will remember not only as delicious, but also want to bring their loved ones back to experience for themselves. So linger over brunch with your friends, flirt over one more glass of wine or share a dessert with someone special, because you’re in Verona and it’s time to vivi la bella vita.\ndescription: With our thoughtfully chosen menu and locally sourced ingredients, Verona-Inspired Italian strives to deliver cuisine that is fresh and uncomplicated, yet unique and refined; honest and spirited food and drinks that our nearby neighbors and out of town guests will remember not only as delicious, but also want to bring their loved ones back to experience for themselves. So linger over brunch with your friends, flirt over one more glass of wine or share a dessert with someone special, because you’re in Verona and it’s time to vivi la bella vita.\n",
        "id": 2,
        "lat": 42.5617299,
        "lng": -83.1468919,
        "name": "Kona Grill - Troy",
        "num_of_reviews": 0,
        "phone_number": "(248) 619-9060",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43mIGRcAPxV5QpLYk3rNXBTz-nwzVyF6-8fYqI8pZJa-I4YfRk-8HZnh34ZeH9nSArMQCiwGDXQjBD5tcFH3drveWeJ75RbfIo=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "17440 Hall Rd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Welcome to Kona Grill Troy, a top restaurant and sushi bar in Detroit where you can enjoy a local paradise. Fresh, wild caught fish is used to craft award-winning sushi, while contemporary American entrees are prepared from scratch in-house. Happy hour on the beautiful, shaded patio overlooking the plaza fountain is a must. And don’t leave until you’ve tried one of the handcrafted cocktails, ice cold draft beer, or a glass of wine selected from the extensive drink menu. The restaurant’s diverse menu and contemporary ambience provide the perfect venue for special occasions like bridal showers, baby showers, birthday celebrations, business meetings, date night, or just any occasion really.\ndescription: Welcome to Kona Grill Troy, a top restaurant and sushi bar in Detroit where you can enjoy a local paradise. Fresh, wild caught fish is used to craft award-winning sushi, while contemporary American entrees are prepared from scratch in-house. Happy hour on the beautiful, shaded patio overlooking the plaza fountain is a must. And don’t leave until you’ve tried one of the handcrafted cocktails, ice cold draft beer, or a glass of wine selected from the extensive drink menu. The restaurant’s diverse menu and contemporary ambience provide the perfect venue for special occasions like bridal showers, baby showers, birthday celebrations, business meetings, date night, or just any occasion really.\n",
        "id": 3,
        "lat": 42.62592609999999,
        "lng": -82.9444754,
        "name": "Cooper’s Hawk Winery & Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(586) 464-9463",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40mFjXgA0In8-1M852xXU9UXzoh5rtCKAhzRIK5vVWYcSPJKvMpuxbGev63zZ9GoAAxMpZJcn_LhZmBlVZanrWIPEXcNJoG42U=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "151 E Big Beaver Rd, Troy, MI 48083, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Cooper’s Hawk Winery & Restaurant combines modern, casual dining with award-winning, handcrafted wines. Our menu features fresh contemporary-American fare infused with flavors from around the world. From appetizers to desserts, each dish on our menu is listed with a bin number to help guide you to your selection’s perfect wine match. In addition to dining, Cooper’s Hawk offers a full-service bar, private party spaces, and Napa-style tasting room with specialty gift store, where guests can enjoy sipping and sampling wines in a traditional winery setting. Sourcing the highest quality grapes from the best vineyards around the world has earned Cooper’s Hawk a growing list of more than 200 wine awards.\ndescription: Cooper’s Hawk Winery & Restaurant combines modern, casual dining with award-winning, handcrafted wines. Our menu features fresh contemporary-American fare infused with flavors from around the world. From appetizers to desserts, each dish on our menu is listed with a bin number to help guide you to your selection’s perfect wine match. In addition to dining, Cooper’s Hawk offers a full-service bar, private party spaces, and Napa-style tasting room with specialty gift store, where guests can enjoy sipping and sampling wines in a traditional winery setting. Sourcing the highest quality grapes from the best vineyards around the world has earned Cooper’s Hawk a growing list of more than 200 wine awards.\n",
        "id": 4,
        "lat": 42.56292550000001,
        "lng": -83.1447013,
        "name": "Cooper's Hawk Winery & Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(248) 781-8811",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42Rg4E7F4reWH4CAgwWMD4_y4tfd-5x5gwaI-FJCX8-Hp2KzbzcI0TUjS_xqosE3Z59_x49_AMKfHhRrox0nSD4L0n2D6ab6HM=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "17430 Hall Rd, Sterling Heights, MI 48038, USA",
        "capacity": 20,
        "city": "Sterling Heights",
        "description": "Brio Partridge Creek is a premier Tuscan-inspired restaurant destination serving authentic, northern Italian cuisine, luxury wines & cocktails—our specialties include premium quality steaks, chops, seafood, made-to-order pasta and flatbreads prepared in an authentic Italian wood-burning oven.\ndescription: Brio Partridge Creek is a premier Tuscan-inspired restaurant destination serving authentic, northern Italian cuisine, luxury wines & cocktails—our specialties include premium quality steaks, chops, seafood, made-to-order pasta and flatbreads prepared in an authentic Italian wood-burning oven.\n",
        "id": 5,
        "lat": 42.62655900000001,
        "lng": -82.9456857,
        "name": "Brio Italian Grille",
        "num_of_reviews": 0,
        "phone_number": "(586) 263-7310",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj405vNeu-fXkUhei91QxjhTSSoD7h61NlBjE_j9zPBgtWhhQVh_abN6Y61gZ9hhboTWTGZvY19urF7P7Pt1ttQCApprKg-GUGNI=s1600-w1000",
        "rating": 5,
        "type": "Italian"
    },
    {
        "address": "75 Macomb Pl, Mt Clemens, MI 48043, USA",
        "capacity": 20,
        "city": "Mt Clemens",
        "description": "Bath City Bistro provides a unique dining and diversion experience for the Metro Detroit area, centered on the Belgian sport of Feather Bowling. This fun activity is coupled with a menu concentrating on steaks, pizza, the obligatory mussels, and a variety of foods to attract patrons of all palates. And of course, your favorite adult beverages.\ndescription: Bath City Bistro provides a unique dining and diversion experience for the Metro Detroit area, centered on the Belgian sport of Feather Bowling. This fun activity is coupled with a menu concentrating on steaks, pizza, the obligatory mussels, and a variety of foods to attract patrons of all palates. And of course, your favorite adult beverages.\n\nOur warm and attractive décor is intended as an unrivaled blend of the turn of the century architecture of Mt. Clemens, featuring photographs that highlight its rich heritage when it was known as “Bath City, U.S.A” for its mineral bath houses. The original brick and wood accents of the building have been restored to convey a sense of warmth and friendliness.\n\nBath City Bistro features three lanes of Belgian Feather Bowling, a Belgian sport that could be described as a cross between bocci ball and shuffleboard.\n",
        "id": 6,
        "lat": 42.5985573,
        "lng": -82.87908829999999,
        "name": "Bath City Bistro",
        "num_of_reviews": 0,
        "phone_number": "(586) 469-0917",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42L2YZmKAwFG0A3mdEaojpD2i4-oZOMYfZQ4ZwlWyARHpDUXthvHWKEWhb5Tq8Ghi85x1GGkhxvWPs9w9MU2f6VbHXMi_gNikE=s1600-w960",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "36470 Jefferson Ave, Harrison Twp, MI 48045, USA",
        "capacity": 20,
        "city": "Harrison Twp",
        "description": "Voted #1 Fish & Chips and Best Seafood by Macomb Daily.\ndescription: Voted #1 Fish & Chips and Best Seafood by Macomb Daily.\n\n\n\nOur kitchen is filled with talented Chefs who work tirelessly on plate presentation and quality standards. The process begins with our chef hand cutting large atlantic cod loins, then battering and cooking the cod fresh for each order.\n",
        "id": 7,
        "lat": 42.5661392,
        "lng": -82.8422851,
        "name": "Terry's Terrace",
        "num_of_reviews": 0,
        "phone_number": "(586) 463-2671",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43HdvlU2_NX6MjFjo0zNnFAMZ9yIR7xNlNnYrRo1OFEUDnLMuZdIKcCtGyCUzAIO_L3FwMoaeaYdr15LfBjEsYfxzPBrxWI4Vo=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "17390 Hall Rd Unit R-103, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "We are an Asian & Chinese restaurant offering dine-in, takeout, to-go, delivery, and catering. Make a reservation online to dine in. Order Asian and Chinese food delivery, takeout, and catering online or through the P.F. Chang's mobile app. Let us cater the perfect feast for you - corporate office catering menus are also available. P.F. Chang’s offers a variety of signature Asian, Thai, Korean, Japanese, Mongolian, and Chinese food dishes including Chicken Lettuce Wraps, Chicken Pad Thai, Signature Lo Mein, Fried Rice, Mongolian Beef, Chang's Spicy Chicken, and Pork and Shrimp Dumplings. Order online for sushi delivery and takeout. Many gluten-free and vegetarian menu items are available. Try our seasonal cocktails and seasonal menu items.\ndescription: We are an Asian & Chinese restaurant offering dine-in, takeout, to-go, delivery, and catering. Make a reservation online to dine in. Order Asian and Chinese food delivery, takeout, and catering online or through the P.F. Chang's mobile app. Let us cater the perfect feast for you - corporate office catering menus are also available. P.F. Chang’s offers a variety of signature Asian, Thai, Korean, Japanese, Mongolian, and Chinese food dishes including Chicken Lettuce Wraps, Chicken Pad Thai, Signature Lo Mein, Fried Rice, Mongolian Beef, Chang's Spicy Chicken, and Pork and Shrimp Dumplings. Order online for sushi delivery and takeout. Many gluten-free and vegetarian menu items are available. Try our seasonal cocktails and seasonal menu items.\n",
        "id": 8,
        "lat": 42.6265339,
        "lng": -82.94633520000001,
        "name": "P.F. Chang's",
        "num_of_reviews": 0,
        "phone_number": "(586) 263-0860",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj416DB2bmCiD0rk3kXZO9FCZsxJ85jLYWMi-UhazH08pzXMCPc-8MnTOsi6f2KK3qmFJxIrWQMROoxGKVXnS4fatRBY4-2Rf5UM=s1600-w1000",
        "rating": 5,
        "type": "Asian"
    },
    {
        "address": "34250 Groesbeck Hwy, Clinton Twp, MI 48035, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Harbor House features the freshest seafood and all you can eat options daily. Come on in and enjoy a drink from our full bar while enjoying the freshest seafood available. \ndescription: Harbor House features the freshest seafood and all you can eat options daily. Come on in and enjoy a drink from our full bar while enjoying the freshest seafood available. \n",
        "id": 9,
        "lat": 42.5486179,
        "lng": -82.9272337,
        "name": "Harbor House Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(586) 791-6070",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj41_8xVMytPEGhNtGv7sKn6leP_JXY58bf_nFuHEXgXIxVcBrsEpzZHVeLa6PJ6HtL8P6DkqjY6qjC-ju5B_zH0-9pSjvMSOn7Q=s1600-w1000",
        "rating": 5,
        "type": "Seafood"
    },
    {
        "address": "13411 15 Mile Rd, Sterling Heights, MI 48312, USA",
        "capacity": 20,
        "city": "Sterling Heights",
        "description": "Rendezvous Restaurant\ndescription: Rendezvous Restaurant\n36217 S Gratiot Ave\nClinton Twp MI 48035\n586-913-7701\n",
        "id": 10,
        "lat": 42.5534819,
        "lng": -82.9905473,
        "name": "Cloverleaf Pizza",
        "num_of_reviews": 0,
        "phone_number": "(586) 264-9700",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40vKy7rEfSAorKuuJ6_4zWzFpP5ispy3erfVlKxXZntN5h2b_Ir2Td-BZT82lgkaSTVPBL3GXvh0gf5OpE1XccwxZPOpi7w7fw=s1600-w1000",
        "rating": 5,
        "type": "1 review"
    },
    {
        "address": "49521 Van Dyke Ave, Shelby Township, MI 48317, USA",
        "capacity": 20,
        "city": "Shelby Twp",
        "description": "Da Francesco's Ristorante and Bar serves classic recipes in a family friendly location that includes a full bar with a beautiful selection of domestic and Italian imported wines. Guests can stop in for lunch and dinner and enjoy the rustic decor paired with homemade dishes that have been passed down through the Belcastro family. We offer a kids and gluten-free menu so everyone can find a favorite on the menu. We offer plenty of bread and soup or salad before starting their meal, or visitors can start with the appetizers, which include Arancini di Riso, Mamma's Meatballs, Fried Calamari, Sausage and Hot Peppers and more. The menu features specialties like the Ravioli con Sugo, Eggplant or Pollo Parmigiana and Gnocci! We also offer plenty of meat and fish choices, including steak alla Francesco, Domenics Filet Mignon, Perch Lemone and Parmigiana Pickerel. Lastly, to end your night just right, finish it off with Mamma Sue's Homemade Tiramisu and a fresh Italian Cappuccino!\ndescription: Da Francesco's Ristorante and Bar serves classic recipes in a family friendly location that includes a full bar with a beautiful selection of domestic and Italian imported wines. Guests can stop in for lunch and dinner and enjoy the rustic decor paired with homemade dishes that have been passed down through the Belcastro family. We offer a kids and gluten-free menu so everyone can find a favorite on the menu. We offer plenty of bread and soup or salad before starting their meal, or visitors can start with the appetizers, which include Arancini di Riso, Mamma's Meatballs, Fried Calamari, Sausage and Hot Peppers and more. The menu features specialties like the Ravioli con Sugo, Eggplant or Pollo Parmigiana and Gnocci! We also offer plenty of meat and fish choices, including steak alla Francesco, Domenics Filet Mignon, Perch Lemone and Parmigiana Pickerel. Lastly, to end your night just right, finish it off with Mamma Sue's Homemade Tiramisu and a fresh Italian Cappuccino!\n",
        "id": 11,
        "lat": 42.65900389999999,
        "lng": -83.0343753,
        "name": "Da Francesco's Ristorante & Bar",
        "num_of_reviews": 0,
        "phone_number": "(586) 731-7544",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40H_RF8ck6WQh8pcCoIqAwW9Hjxw_cnjJ2jCqAS7UOLEGP2yp0Ewjo2ppNQ03crBhHuLt3fqZKkjlR3JWZxaIPc193M92VGBPs=s1600-w1000",
        "rating": 5,
        "type": "Italian"
    },
    {
        "address": "2915 Coolidge Hwy, Troy, MI 48084, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Located at the intersection of Big Beaver Road and Coolidge Highway across from the Somerset Collection shopping center, Ocean Prime is a nationally acclaimed, modern American restaurant & lounge from the award-winning Cameron Mitchell Restaurants. Stunning settings, an impressive menu of seafood & steaks, and genuine hospitality make Ocean Prime the ideal place to socialize, talk business, celebrate & indulge. Reservations are recommended.\ndescription: Located at the intersection of Big Beaver Road and Coolidge Highway across from the Somerset Collection shopping center, Ocean Prime is a nationally acclaimed, modern American restaurant & lounge from the award-winning Cameron Mitchell Restaurants. Stunning settings, an impressive menu of seafood & steaks, and genuine hospitality make Ocean Prime the ideal place to socialize, talk business, celebrate & indulge. Reservations are recommended.\n\nOcean Prime strives to provide an elegant, fine dining atmosphere. Our associates’ priority is to ensure your experience is memorable. We ask that our guests choose attire that is both polished and suited to our restaurant.\nTHANK YOU FOR NOT WEARING:\nClothing emitting excessive marijuana odor\nExcessively revealing clothing or exposed undergarments\nClothing with offensive language or graphics\nAdmittance to Ocean Prime is at the discretion of management who reserves the right to refuse service to patrons who are inappropriately dressed.\n",
        "id": 12,
        "lat": 42.56048969999999,
        "lng": -83.1874242,
        "name": "Ocean Prime Detroit",
        "num_of_reviews": 0,
        "phone_number": "(248) 458-0500",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40WT2U8RwvxAVn8WSB6sXsI96y646UnasYnR9Mu_ewyhRVZE2s6VNzNcg-G8JeVdalW1l8dLabxQMJPpN86IekusTgKUhzffOc=s1600-w845",
        "rating": 5,
        "type": "Seafood"
    },
    {
        "address": "2100 W Big Beaver Rd, Troy, MI 48084, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Eddie V's Prime Seafood brings an experience filled with Seafood, Steaks and Rhythm, with a menu emphasis on top of the catch prime seafood creations, USDA prime beef and chops, and fresh oyster bar selections. The restaurant is set in a relaxed, elegant atmosphere accented with a palette of sultry earth tones occasionally interrupted by bold colored artwork and mixed wood finishes.\ndescription: Eddie V's Prime Seafood brings an experience filled with Seafood, Steaks and Rhythm, with a menu emphasis on top of the catch prime seafood creations, USDA prime beef and chops, and fresh oyster bar selections. The restaurant is set in a relaxed, elegant atmosphere accented with a palette of sultry earth tones occasionally interrupted by bold colored artwork and mixed wood finishes.\n",
        "id": 13,
        "lat": 42.5621239,
        "lng": -83.17625500000001,
        "name": "Eddie V's Prime Seafood",
        "num_of_reviews": 0,
        "phone_number": "(248) 649-7319",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43zW_chPggoPOJW4Sqe4XBhdTvuNwIKpotk5QimRhJPUbTKb6qmD9S-Bo3FZ099uaOeg05w_vTAtt2_SV2gRt449lxjUijU_1g=s1600-w1000",
        "rating": 5,
        "type": "Oyster Bar"
    },
    {
        "address": "1000 W Big Beaver Rd, Troy, MI 48084, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Seasons 52 is a comfortable and stylish fresh grill and wine bar offering a refreshingly balanced approach to dining where guests are free to enjoy, knowing any choice they make is one they’ll feel good about. The menu changes with the season to feature ingredients at their peak, from whole produce that arrives and is kept 100% fresh, never frozen, to carefully sourced meats and pristine seafood. Entrées are oak-fire grilled or brick oven-roasted, without a fryer in sight, to be flavorful and naturally lighter, and the Wine Bar pours 52 world-class wines by glass and signature cocktails. Lunch and dinner daily, happy hour Mondays – Friday.\ndescription: Seasons 52 is a comfortable and stylish fresh grill and wine bar offering a refreshingly balanced approach to dining where guests are free to enjoy, knowing any choice they make is one they’ll feel good about. The menu changes with the season to feature ingredients at their peak, from whole produce that arrives and is kept 100% fresh, never frozen, to carefully sourced meats and pristine seafood. Entrées are oak-fire grilled or brick oven-roasted, without a fryer in sight, to be flavorful and naturally lighter, and the Wine Bar pours 52 world-class wines by glass and signature cocktails. Lunch and dinner daily, happy hour Mondays – Friday.\n",
        "id": 14,
        "lat": 42.56277780000001,
        "lng": -83.166823,
        "name": "Seasons 52",
        "num_of_reviews": 0,
        "phone_number": "(248) 362-9752",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40bGR7CoayN3gjJk-D-KCxqIt4wSCVUzGvFlgUG1ndIUlJ8LPewv6zQ5rKO8UWHpb3kSocqwf1kfmTpe0pcIR_-TuTB1KJDJqA=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "17440 Hall Rd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Cooper’s Hawk Winery & Restaurant combines modern, casual dining with award-winning, handcrafted wines. Our menu features fresh contemporary-American fare infused with flavors from around the world. From appetizers to desserts, each dish on our menu is listed with a bin number to help guide you to your selection’s perfect wine match. In addition to dining, Cooper’s Hawk offers a full-service bar, private party spaces, and Napa-style tasting room with specialty gift store, where guests can enjoy sipping and sampling wines in a traditional winery setting. Sourcing the highest quality grapes from the best vineyards around the world has earned Cooper’s Hawk a growing list of more than 200 wine awards.\ndescription: Cooper’s Hawk Winery & Restaurant combines modern, casual dining with award-winning, handcrafted wines. Our menu features fresh contemporary-American fare infused with flavors from around the world. From appetizers to desserts, each dish on our menu is listed with a bin number to help guide you to your selection’s perfect wine match. In addition to dining, Cooper’s Hawk offers a full-service bar, private party spaces, and Napa-style tasting room with specialty gift store, where guests can enjoy sipping and sampling wines in a traditional winery setting. Sourcing the highest quality grapes from the best vineyards around the world has earned Cooper’s Hawk a growing list of more than 200 wine awards.\n",
        "id": 15,
        "lat": 42.62592609999999,
        "lng": -82.9444754,
        "name": "Cooper’s Hawk Winery & Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(586) 464-9463",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40mFjXgA0In8-1M852xXU9UXzoh5rtCKAhzRIK5vVWYcSPJKvMpuxbGev63zZ9GoAAxMpZJcn_LhZmBlVZanrWIPEXcNJoG42U=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "151 E Big Beaver Rd, Troy, MI 48083, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Now Open: We look forward to serving you soon.\ndescription: Now Open: We look forward to serving you soon.\n\nRuth's Chris Steak House in Troy, MI serves the finest USDA Prime beef available, broiled at 1,800° and served on 500° plates, so your steak stays hot, juicy and delicious from first bite to last. Enjoy our New Orleans-inspired appetizers, USDA Prime steaks, fresh seafood, signature side dishes and homemade desserts. All this while you enjoy our warm, inviting atmosphere and Ruth’s Chris’ genuine hospitality. So whether you’re a regular or have just been wondering what all the buzz is about, Ruth's Chris is the perfect excuse to enjoy the perfect night out. Dinner is served nightly, reservations are suggested and private dining and offsite catering may be arranged.\n",
        "id": 16,
        "lat": 42.56292550000001,
        "lng": -83.1447013,
        "name": "Cooper's Hawk Winery & Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(248) 781-8811",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42Rg4E7F4reWH4CAgwWMD4_y4tfd-5x5gwaI-FJCX8-Hp2KzbzcI0TUjS_xqosE3Z59_x49_AMKfHhRrox0nSD4L0n2D6ab6HM=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "755 W Big Beaver Rd Suite 151, Troy, MI 48084, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Warm alehouse with patio offering craft beer from a long list, plus an elevated tavern menu. Men's Journal Voted the Beer Cheese Burger Top 25 in America. Please note, patio seats are not reservable but will we will do our best to accommodate your request. \ndescription: Warm alehouse with patio offering craft beer from a long list, plus an elevated tavern menu. Men's Journal Voted the Beer Cheese Burger Top 25 in America. Please note, patio seats are not reservable but will we will do our best to accommodate your request. \n",
        "id": 17,
        "lat": 42.5603213,
        "lng": -83.16155529999999,
        "name": "Ruth's Chris Steak House",
        "num_of_reviews": 0,
        "phone_number": "(248) 269-8424",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40h3FJLUPIQmKWa_K7LUn9mLRwBlCzkd1uhWg3cJMabKKDhGu4b-CoFDjir1zOKGY7_fMk1nL50NJFgmfXvUGi1q0v6gLxweYA=s1600-w1000",
        "rating": 5,
        "type": "Steakhouse"
    },
    {
        "address": "316 S Main St, Royal Oak, MI 48067, USA",
        "capacity": 20,
        "city": "Royal Oak",
        "description": "Classic Pub and Oyster Bar with a Focus on Wine, Craft Beer and Fresh Seafood and Oysters. Please note, patio seats are not reservable but will we will do our best to accommodate your request. \ndescription: Classic Pub and Oyster Bar with a Focus on Wine, Craft Beer and Fresh Seafood and Oysters. Please note, patio seats are not reservable but will we will do our best to accommodate your request. \n",
        "id": 18,
        "lat": 42.4876295,
        "lng": -83.1443717,
        "name": "Ale Mary's Beer Hall",
        "num_of_reviews": 0,
        "phone_number": "(248) 268-1939",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj407m1hzP8OINDl4zlwRO_i8z-tLREahaOh3wvLAppP_IBf_7Q4GbVMpJILu3QaZ0NMcZn5TY0-DazDcdNpSrnsg3fMkqlx1-GI=s1600-w720",
        "rating": 5,
        "type": "Beer Garden"
    },
    {
        "address": "318 S Main St, Royal Oak, MI 48067, USA",
        "capacity": 20,
        "city": "Royal Oak",
        "description": "Mediterranean with an Israeli influence. In an eclectic enviroment. Our Kitchen closes nightly at 11:00 PM (9:00 PM on Sundays). Located in the heart of Royal Oak featuring a full bar and eclectic decor. Covered patio seating available along Main St. Blocks from the Royal Oak Music Theater and Stagecrafters Baldwin Theater. We look forward to seeing you!\ndescription: Mediterranean with an Israeli influence. In an eclectic enviroment. Our Kitchen closes nightly at 11:00 PM (9:00 PM on Sundays). Located in the heart of Royal Oak featuring a full bar and eclectic decor. Covered patio seating available along Main St. Blocks from the Royal Oak Music Theater and Stagecrafters Baldwin Theater. We look forward to seeing you!\n",
        "id": 19,
        "lat": 42.4875952,
        "lng": -83.1444932,
        "name": "Tom's Oyster Bar",
        "num_of_reviews": 0,
        "phone_number": "(248) 541-1186",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43nDPuMgIlt3RyNvCT3eg9uLieRHZHZeYDMgef6fpObAbzcKGs8I7SFL7MRcpvvleQeQBJP33LTCrhjHIa772hOwR0stfusIKo=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "312 S Main St, Royal Oak, MI 48067, USA",
        "capacity": 20,
        "city": "Royal Oak",
        "description": "Coming Soon! \ndescription: Coming Soon! \n",
        "id": 20,
        "lat": 42.4876744,
        "lng": -83.1444951,
        "name": "Mesa Tacos and Tequila",
        "num_of_reviews": 0,
        "phone_number": "(248) 545-1940",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40FJDwPgdvO4bbForLN7T-HHtHBFQpc6gR-v2KdfGc4KbhaGjmPPBQ0uPB7xButwN_oVm7vFE_lzGNUrCHp9EhcZROB4hqqJdc=s1600-w1000",
        "rating": 5,
        "type": "Mexican"
    },
    {
        "address": "6545 Orchard Lake Rd, West Bloomfield Township, MI 48322, USA",
        "capacity": 20,
        "city": "West Bloomfield Township",
        "description": "Prime29 - West Bloomfield\ndescription: Prime29 - West Bloomfield\nContemporary, Casual-Fine Dining. At Prime29 Steakhouse we serve only the best cuts of prime beef, aged 29 days and fresh seafood together with exemplary wines and top shelf martinis and cocktails. We also feature market fresh vegetarian & gluten free chef's compositions. At Prime29 Steakhouse we are passionate about delivering a world class dining experience with striking dinner and dessert compositions, exceptional tableside service, and exclusive drink pairings from start to finish.\n\nPrime29 Steakhouse, located at the corner of Orchard Lake Rd and Maple also features a gorgeous outdoor covered patio showcasing a 10ft, 360 degree fireplace; a spacious lounge, and 3 beautiful dining rooms perfect for parties up to 200.\n",
        "id": 21,
        "lat": 42.5426055,
        "lng": -83.35877769999999,
        "name": "Prime29 Steakhouse",
        "num_of_reviews": 0,
        "phone_number": "(248) 737-7463",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42CoJhbTE1NR8H-rouFhlJa5nHVvAet74GioVs1E6R8-SBqxb8UwQhECr0zyxRrU7hl_9xY1FVdlG5IKXSCCffBqSWZ08C_mCs=s1600-w1000",
        "rating": 5,
        "type": "Steakhouse"
    },
    {
        "address": "9550 Riverside Dr E, Windsor, ON N8P 1A1, Canada",
        "capacity": 20,
        "city": "Windsor",
        "description": "Harbour House is located on the beautiful Detroit River at Lakeview Marina right across from the iconic Peche Island. In the location of the legendary Lilly Kazilly's, Harbour House Windsor is a fully updated Hampton Inspired Waterfront Restaurant & Bar. Open for Brunch on weekends and daily for lunch, dinner and late-night cocktails. On weekends expect live entertainment during the day on the 4000 sq ft Waterfront Patio or late night inside their 8000 sq ft dining and bar areas. Harbour House also has 5 boat docks reserved and designated for 40ft and 50ft boats/yachts. You can dock your boat at the brand new multi-million-dollar Lakeview Marina. Call about slips - located right in front of our patio. Also providing boat side service for anyone at the marina - merely call us at 226-620-0101 to place your order and we will run it out to you.\ndescription: Harbour House is located on the beautiful Detroit River at Lakeview Marina right across from the iconic Peche Island. In the location of the legendary Lilly Kazilly's, Harbour House Windsor is a fully updated Hampton Inspired Waterfront Restaurant & Bar. Open for Brunch on weekends and daily for lunch, dinner and late-night cocktails. On weekends expect live entertainment during the day on the 4000 sq ft Waterfront Patio or late night inside their 8000 sq ft dining and bar areas. Harbour House also has 5 boat docks reserved and designated for 40ft and 50ft boats/yachts. You can dock your boat at the brand new multi-million-dollar Lakeview Marina. Call about slips - located right in front of our patio. Also providing boat side service for anyone at the marina - merely call us at 226-620-0101 to place your order and we will run it out to you.\n",
        "id": 22,
        "lat": 42.3392918,
        "lng": -82.9280125,
        "name": "Harbour House Waterfront Eatery",
        "num_of_reviews": 0,
        "phone_number": "(226) 620-0101",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40vBcHSaf-hlBAOVomwt57Yr_XhYM3zy1bB48EEmWu5YQpnTuiCqBQqdrXGxXB6PcTkHzccBPo1iHwKtjafKy2oms2kZMUi-x0=s1600-w1000",
        "rating": 5,
        "type": "Seafood"
    },
    {
        "address": "2601 Lauzon Pkwy, Windsor, ON N8T 3M4, Canada",
        "capacity": 20,
        "city": "Windsor",
        "description": "John Max Sports & Wings is Windsor, Ontario's best sports bar.\ndescription: John Max Sports & Wings is Windsor, Ontario's best sports bar.\n\nFace masks are mandatory to enter the restaurant.\n\nWe have a 10 minute grace period. Please call us if you are running late to hold your reservation.\n",
        "id": 23,
        "lat": 42.3104036,
        "lng": -82.9375513,
        "name": "John Max Sports & Wings Lauzon Pkwy",
        "num_of_reviews": 0,
        "phone_number": "(519) 915-1900",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40VwHYwxst3Y4jCPtNbStBeV9e5zEI_l3bf-o1avo-HoGXjQfN0hv9KIxjFAc-su_ofSP3GDT9Vad6sM-yG_K2EjOuNEEpay-8=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "430 Ouellette Ave, Windsor, ON N9A 1B2, Canada",
        "capacity": 20,
        "city": "Windsor",
        "description": "The Largest Irish-Canadian Restaurant Brand. Our warm hospitality welcomes you to a place where you can enjoy the best of both made in-pub food and drink in an atmosphere that encourages sharing good times with family and friends. \ndescription: The Largest Irish-Canadian Restaurant Brand. Our warm hospitality welcomes you to a place where you can enjoy the best of both made in-pub food and drink in an atmosphere that encourages sharing good times with family and friends. \n",
        "id": 24,
        "lat": 42.3160879,
        "lng": -83.0380282,
        "name": "Fionn MacCool's Windsor",
        "num_of_reviews": 0,
        "phone_number": "(226) 315-2398",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43dYAiG4NaJpO_PTDG3gy12rsAoILlERJ53V2uonTA0u8mJdrvqof4wI-zB76eaQ4GCLhUNOPvxca4QvXgngwWY4dD30fA1fzA=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "9 Amy Croft Dr, Tecumseh, ON N9K 1C7, Canada",
        "capacity": 20,
        "city": "Tecumseh",
        "description": "Kelseys has been Canada's Original Roadhouse since 1978. Inspired by the uninhibited spirit of road tripping and the classic Roadhouse, the rules are different at Kelseys. It is where you go to eat what you want to eat, drink what you want to drink, and be who you want to be. Enjoy classics like our legendary spinach dip, fresh double stacked burgers, two-handed sandwiches, and unforgettable chicken wings. Fuel your adventurous spirit that craves something a little different - a little more Original!\ndescription: Kelseys has been Canada's Original Roadhouse since 1978. Inspired by the uninhibited spirit of road tripping and the classic Roadhouse, the rules are different at Kelseys. It is where you go to eat what you want to eat, drink what you want to drink, and be who you want to be. Enjoy classics like our legendary spinach dip, fresh double stacked burgers, two-handed sandwiches, and unforgettable chicken wings. Fuel your adventurous spirit that craves something a little different - a little more Original!\n\nIn the mood for great food, drinks, and a lot of fun? Take a trip down the block to Kelseys.\n",
        "id": 25,
        "lat": 42.3068116,
        "lng": -82.86895040000002,
        "name": "Kelseys Original Roadhouse",
        "num_of_reviews": 0,
        "phone_number": "(519) 735-3390",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj410lX65zbU_fNN8lz2s5PqZfBZf8KVoBV28AB8tsESMVSxrpSGQvQVeDXT3YwUuGpFgChv-L5xAum5HSqarr3EdrLAxzGNmDQw=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "4707 White Lake Rd, Independence Charter Township, MI 48346, USA",
        "capacity": 20,
        "city": "Independence Charter Township",
        "description": "We serve Mediterranean and american cuisine. We have 101 rotating tap handles with craft beers and sodas. We have 4 bowling lanes, a virtual golf room, and virtual reality games. We also have an amazing patio that is used all year round. Whether you are looking to go out to dinner on a regular day or have a special event, this is the place for you. ALL GAMING RESERVATIONS MUST BE MADE BY CALLING THE RESTAURANT. NO ONLINE GAMING RESERVATIONS WILL BE HONORED.\ndescription: We serve Mediterranean and american cuisine. We have 101 rotating tap handles with craft beers and sodas. We have 4 bowling lanes, a virtual golf room, and virtual reality games. We also have an amazing patio that is used all year round. Whether you are looking to go out to dinner on a regular day or have a special event, this is the place for you. ALL GAMING RESERVATIONS MUST BE MADE BY CALLING THE RESTAURANT. NO ONLINE GAMING RESERVATIONS WILL BE HONORED.\n",
        "id": 26,
        "lat": 42.7049183,
        "lng": -83.44257929999999,
        "name": "Alex's Gourmet Market",
        "num_of_reviews": 0,
        "phone_number": "(248) 297-5520",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40ryNPgWCywgHtOZysr7Ybh_ak9kdqC_dD-dJQ7lmHHu0jinlOCN0evLbYacoqL_30qX_Z6HOZu7Ej1-8tGJPxyqFZNyoNIQm0=s1600-w1000",
        "rating": 5,
        "type": "Mediterranean"
    },
    {
        "address": "5355 Wyandotte St E, Windsor, ON N8S 1L6, Canada",
        "capacity": 20,
        "city": "Windsor",
        "description": "Tucked in the heart of Canada’s Southern most town, is our 1859 historic home in Kingsville, Ontario, that has been fully restored, while still keeping its 19th century charm.\ndescription: Tucked in the heart of Canada’s Southern most town, is our 1859 historic home in Kingsville, Ontario, that has been fully restored, while still keeping its 19th century charm.\nDon’t miss out on our fully screened and heated patio, open all year long!\n",
        "id": 27,
        "lat": 42.3277876,
        "lng": -82.97140879999999,
        "name": "Thompson Manor",
        "num_of_reviews": 0,
        "phone_number": "(519) 948-9007",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj41TIbAaiiIrIlTGOlB9xSCNar1KNb1ekMliMEvWhhgDuMJ6shBeXMP3SsZoi1auc1xXhTqxK2j9va2mOe3x6ipTHwFeGVmTDVc=s1600-w1000",
        "rating": 5,
        "type": "Steakhouse"
    },
    {
        "address": "76 Main St E, Kingsville, ON N9Y 1A2, Canada",
        "capacity": 20,
        "city": "Kingsville",
        "description": "Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\ndescription: Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\n",
        "id": 28,
        "lat": 42.03827860000001,
        "lng": -82.7364211,
        "name": "Thompson Manor Steak and Seafood",
        "num_of_reviews": 0,
        "phone_number": "(519) 712-9511",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42OS7FNGuR-3o7HVg2eo6uHvY4x1HfC5wdcct_Y-4lwZ4PU282l1kqgp9yiqysucz0kJ9DWeuMlcGRjIa7EXKPTKtfrWOcKBA=s1600-w988",
        "rating": 5,
        "type": "Steakhouse"
    },
    {
        "address": "8251 Trillium Circle Avenue STE 102, Grand Blanc, MI 48439, USA",
        "capacity": 20,
        "city": "Grand Blanc",
        "description": "Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\ndescription: Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\n",
        "id": 29,
        "lat": 42.9099259,
        "lng": -83.6267963,
        "name": "Buffalo Wild Wings",
        "num_of_reviews": 0,
        "phone_number": "(810) 603-1299",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40F_pXCuMyneXGc6yaSVUYsTJyFaCpB9lJM9JeP-Fks0uC14GJzZQDoDCrTn9OZJkt0Yj_ozvSksUoqRd7mBRdHJXUvLyuZZBs=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "3190 Silver Lake Rd, Fenton, MI 48430, USA",
        "capacity": 20,
        "city": "Fenton",
        "description": "BurgerFin's unique fusion of Sliders and Sushi offers something for everyone in an upbeat, casual atmosphere. From game time to family time, we're your regular hang out to dine, drink, watch and relax. \ndescription: BurgerFin's unique fusion of Sliders and Sushi offers something for everyone in an upbeat, casual atmosphere. From game time to family time, we're your regular hang out to dine, drink, watch and relax. \n",
        "id": 30,
        "lat": 42.8051584,
        "lng": -83.73264209999999,
        "name": "Buffalo Wild Wings",
        "num_of_reviews": 0,
        "phone_number": "(810) 629-0099",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43l4Tp-Wnbpc0_sCqQ2-vcIUzqFpviZIojNXAyJfdyDsjbSO5sN5eeeu3gbcGSYhu97mUw7t8OMkmgIAtUIPBtueJxv9eVRva4=s1600-w1000",
        "rating": 5,
        "type": "1 review"
    },
    {
        "address": "17380 Hall Rd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Time counts at BJ’s Restaurant & Brewhouse. Since our humble beginnings back in 1978, we’ve continued to refine our brewhouse experience to make BJ’s a place where you can make the most of any meal. We want BJ’s to be a place where the moment you leave is the moment you plan on coming back. We pride ourselves in our craft and attention to detail. Our guests come here for our award-winning handcrafted beer. They come here for the Southern California twist we’ve put on the Chicago-style deep dish pizza. And they come here for our Pizookies®, our world-renowned dessert. But above all we know people come here to make their good times better. So in many ways we haven’t just crafted a brand, but a mindset. And our guests are the reason for this. And it’s because of them we’re continually striving to make sure every moment they choose to spend with us counts. Welcome to BJ’s, a restaurant with a Brewhouse soul.\ndescription: Time counts at BJ’s Restaurant & Brewhouse. Since our humble beginnings back in 1978, we’ve continued to refine our brewhouse experience to make BJ’s a place where you can make the most of any meal. We want BJ’s to be a place where the moment you leave is the moment you plan on coming back. We pride ourselves in our craft and attention to detail. Our guests come here for our award-winning handcrafted beer. They come here for the Southern California twist we’ve put on the Chicago-style deep dish pizza. And they come here for our Pizookies®, our world-renowned dessert. But above all we know people come here to make their good times better. So in many ways we haven’t just crafted a brand, but a mindset. And our guests are the reason for this. And it’s because of them we’re continually striving to make sure every moment they choose to spend with us counts. Welcome to BJ’s, a restaurant with a Brewhouse soul.\n",
        "id": 31,
        "lat": 42.625928,
        "lng": -82.9475927,
        "name": "BurgerFin Partridge Creek",
        "num_of_reviews": 0,
        "phone_number": "(586) 422-0085",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40mvmtwpcBHF_jXO19RGpB6pZAJ06cKWnmVT_cMFfbiHHmhS1gthA7IoZICcEkzWf0rME5ywJJHhC1xgt2HN5PvgZY9t7F_3tA=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "14455 Lakeside Cir, Sterling Heights, MI 48313, USA",
        "capacity": 20,
        "city": "Sterling Heights",
        "description": "We are an Asian & Chinese restaurant offering dine-in, takeout, to-go, delivery, and catering. Make a reservation online to dine in. Order Asian and Chinese food delivery, takeout, and catering online or through the P.F. Chang's mobile app. Let us cater the perfect feast for you - corporate office catering menus are also available. P.F. Chang’s offers a variety of signature Asian, Thai, Korean, Japanese, Mongolian, and Chinese food dishes including Chicken Lettuce Wraps, Chicken Pad Thai, Signature Lo Mein, Fried Rice, Mongolian Beef, Chang's Spicy Chicken, and Pork and Shrimp Dumplings. Order online for sushi delivery and takeout. Many gluten-free and vegetarian menu items are available. Try our seasonal cocktails and seasonal menu items.\ndescription: We are an Asian & Chinese restaurant offering dine-in, takeout, to-go, delivery, and catering. Make a reservation online to dine in. Order Asian and Chinese food delivery, takeout, and catering online or through the P.F. Chang's mobile app. Let us cater the perfect feast for you - corporate office catering menus are also available. P.F. Chang’s offers a variety of signature Asian, Thai, Korean, Japanese, Mongolian, and Chinese food dishes including Chicken Lettuce Wraps, Chicken Pad Thai, Signature Lo Mein, Fried Rice, Mongolian Beef, Chang's Spicy Chicken, and Pork and Shrimp Dumplings. Order online for sushi delivery and takeout. Many gluten-free and vegetarian menu items are available. Try our seasonal cocktails and seasonal menu items.\n",
        "id": 32,
        "lat": 42.6263892,
        "lng": -82.9839666,
        "name": "BJ's Restaurant & Brewhouse",
        "num_of_reviews": 0,
        "phone_number": "(586) 519-6250",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj41y4DV1c70bcpRsLlNmV53aC4fb3RlaGLw744FxKbykC_TGzAbJ1IMeZqUkUuRrhITFjDCNvJq-2Cmn6HGQVug8WtftjzQ_hTA=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "19470 Haggerty Rd, Livonia, MI 48152, USA",
        "capacity": 20,
        "city": "Livonia",
        "description": "Harbor House features the freshest seafood and all you can eat options daily. Come on in and enjoy a drink from our full bar while enjoying the freshest seafood available. \ndescription: Harbor House features the freshest seafood and all you can eat options daily. Come on in and enjoy a drink from our full bar while enjoying the freshest seafood available. \n",
        "id": 33,
        "lat": 42.4278121,
        "lng": -83.4324431,
        "name": "BJ's Restaurant & Brewhouse",
        "num_of_reviews": 0,
        "phone_number": "(734) 357-8530",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42nZyZMTL828CY4yGufI70PXoaEv-6cxdOnY9A2d023WeI-bQPENAczSgHrFCejt_A4DGb7Z7iBKQNUvYuSvsqD6S1Xq4VXLyc=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "17390 Hall Rd Unit R-103, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Our authentic BBQ starts in a live-wood smoker stoked with genuine hickory logs. Our pitmasters hand-rub the meats with a custom blend of spices and cook for hours to extract the natural flavors. We source the highest quality meats and trim them up like we’re in a competition and hand-rub them with the freshest seasonings available to create mouthwatering experiences! In addition to our BBQ and grilled meats, our menu features a selection of salads, sandwiches, side items, and made-from-scratch desserts.\ndescription: Our authentic BBQ starts in a live-wood smoker stoked with genuine hickory logs. Our pitmasters hand-rub the meats with a custom blend of spices and cook for hours to extract the natural flavors. We source the highest quality meats and trim them up like we’re in a competition and hand-rub them with the freshest seasonings available to create mouthwatering experiences! In addition to our BBQ and grilled meats, our menu features a selection of salads, sandwiches, side items, and made-from-scratch desserts.\n",
        "id": 34,
        "lat": 42.6265339,
        "lng": -82.94633520000001,
        "name": "P.F. Chang's",
        "num_of_reviews": 0,
        "phone_number": "(586) 263-0860",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj416DB2bmCiD0rk3kXZO9FCZsxJ85jLYWMi-UhazH08pzXMCPc-8MnTOsi6f2KK3qmFJxIrWQMROoxGKVXnS4fatRBY4-2Rf5UM=s1600-w1000",
        "rating": 5,
        "type": "Asian"
    },
    {
        "address": "34250 Groesbeck Hwy, Clinton Twp, MI 48035, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\ndescription: Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\n",
        "id": 35,
        "lat": 42.5486179,
        "lng": -82.9272337,
        "name": "Harbor House Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(586) 791-6070",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj41_8xVMytPEGhNtGv7sKn6leP_JXY58bf_nFuHEXgXIxVcBrsEpzZHVeLa6PJ6HtL8P6DkqjY6qjC-ju5B_zH0-9pSjvMSOn7Q=s1600-w1000",
        "rating": 5,
        "type": "Seafood"
    },
    {
        "address": "20300 E Thirteen Mile Rd, Roseville, MI 48066, USA",
        "capacity": 20,
        "city": "Roseville",
        "description": "Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\ndescription: Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\n",
        "id": 36,
        "lat": 42.524419,
        "lng": -82.9143155,
        "name": "Famous Dave's Bar-B-Que",
        "num_of_reviews": 0,
        "phone_number": "(586) 293-2900",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40ss9AKCUCEbvQeLpqj1zuD4rjE0w_GIDTrcju5ohKCleMKZOTvCadfUaj4ZlcmPJBVU76mHOsx_Z3PXXp8-snnzlTzKBhWaEo=s1600-w315",
        "rating": 5,
        "type": "Barbecue"
    },
    {
        "address": "48 Market St, Mt Clemens, MI 48043, USA",
        "capacity": 20,
        "city": "Mt Clemens",
        "description": "On behalf of Chef Jeff Heinzman CEC AAC and the staff at Gnocchi, we would like to welcome you to our restaurant. For over 40 years Chef Heinzman has been perfecting his recipes, teaching cooking classes, cooking for the stars on movie productions, and running restaurants. Together with our staff and the finest, fresh ingredients; we can assure you will have a great dining experience. We are the only restaurant of its kind in the USA, specializing in homemade Ricotta Gnocchi. We have over 40 different choices of Gnocchi. You can dine-in, carry out, or we have our Gnocchi quick frozen and sold by the pound.\ndescription: On behalf of Chef Jeff Heinzman CEC AAC and the staff at Gnocchi, we would like to welcome you to our restaurant. For over 40 years Chef Heinzman has been perfecting his recipes, teaching cooking classes, cooking for the stars on movie productions, and running restaurants. Together with our staff and the finest, fresh ingredients; we can assure you will have a great dining experience. We are the only restaurant of its kind in the USA, specializing in homemade Ricotta Gnocchi. We have over 40 different choices of Gnocchi. You can dine-in, carry out, or we have our Gnocchi quick frozen and sold by the pound.\n",
        "id": 37,
        "lat": 42.5990802,
        "lng": -82.8757133,
        "name": "Buffalo Wild Wings",
        "num_of_reviews": 0,
        "phone_number": "(586) 469-0725",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42LpwLbZZ92fznGad75OheqafbSwO40oab3KmWCnMQiGyy8XDrg2_i2pNxm7WrTBvhYRLm79O-2-sLcXbhe9O2WUvaVHVXyHf0=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "15745 15 Mile Rd, Clinton Twp, MI 48035, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Coming Soon! \ndescription: Coming Soon! \n",
        "id": 38,
        "lat": 42.5537207,
        "lng": -82.9636486,
        "name": "Buffalo Wild Wings",
        "num_of_reviews": 0,
        "phone_number": "(586) 293-9500",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43qLVZOTREXeJBndKc4dituc71bZv8s2u-RPmMA2AIrILNU4sGirAIUPsYykmljp4EOLys2i0ROenQW6IXW3F4QVBY6hIHEpCQ=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "46120 Garfield Rd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Gourmet Burgers, Cocktails & More! We look forward to having you! \ndescription: Gourmet Burgers, Cocktails & More! We look forward to having you! \n",
        "id": 39,
        "lat": 42.60276229999999,
        "lng": -82.9518143,
        "name": "Gnocchi Italian Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(586) 741-8443",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40mqhpL1v_5mN3RbzA30ra9yeDBwiPLwfGOK3N5ir52dHKgc3X04wlqXdp5N-7EbGJo6F1bZvXX5CKfFLPOqtBJydpfa0s4IUk=s1600-w640",
        "rating": 5,
        "type": "Italian"
    },
    {
        "address": "424 Cass Ave, Mt Clemens, MI 48043, USA",
        "capacity": 20,
        "city": "Mt Clemens",
        "description": "We hope our pledge to be the best is evident in everything at Sajo’s. We strive to hire talented dedicated employees. Choose the highest quality ingredients and maintain a relaxing and comfortable atmosphere. We do it all with a sense of responsibility and pride in being one of Michigan’s favorite east side restaurants.\ndescription: We hope our pledge to be the best is evident in everything at Sajo’s. We strive to hire talented dedicated employees. Choose the highest quality ingredients and maintain a relaxing and comfortable atmosphere. We do it all with a sense of responsibility and pride in being one of Michigan’s favorite east side restaurants.\n\nWe are opened and ready to go. We are Covid 19 compliant. Please bare with us during these times as we are limited to 50% capacity and we will do our best to take care of our guests and staff in a safe professional manner.\n",
        "id": 40,
        "lat": 42.5991264,
        "lng": -82.8985046,
        "name": "China 1",
        "num_of_reviews": 0,
        "phone_number": "(586) 783-1174",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42liPBk9FlSOCAFpibypQCMdvTPFqNNDxE48_zcAGnJ7sZJDeZN3gofZEdsrJ2BH0Aj9vVSFM-F9QlmKq21WXczKjMYXzVDxoA=s1600-w720",
        "rating": 5,
        "type": "Chinese"
    },
    {
        "address": "43203 Garfield Rd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Eat, drink and be happy—that's the idea at Bar Louie. This contemporary gastropub serves American grub, microbrews, cocktails and other drinks. The restaurant's interior echoes its fun, urban vibe with polished wood finishing and warm lighting. Bar Louie offers an expansive menu that includes salads, sandwiches, burgers and hearty entrees. Start off with some chicken nachos and then order the Chicago stockyard burger for a delicious treat.Great for after-hours drinks with friends, Bar Louie is open up until 1 a.m. between Sunday and Thursday, and extends its closing hours till 2 a.m. on Fridays and Saturdays. This restaurant also offers menu specials through the week.\ndescription: Eat, drink and be happy—that's the idea at Bar Louie. This contemporary gastropub serves American grub, microbrews, cocktails and other drinks. The restaurant's interior echoes its fun, urban vibe with polished wood finishing and warm lighting. Bar Louie offers an expansive menu that includes salads, sandwiches, burgers and hearty entrees. Start off with some chicken nachos and then order the Chicago stockyard burger for a delicious treat.Great for after-hours drinks with friends, Bar Louie is open up until 1 a.m. between Sunday and Thursday, and extends its closing hours till 2 a.m. on Fridays and Saturdays. This restaurant also offers menu specials through the week.\n",
        "id": 41,
        "lat": 42.6142315,
        "lng": -82.95399119999999,
        "name": "Naked Burger",
        "num_of_reviews": 0,
        "phone_number": "(586) 649-7007",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42AYkWZRkJ3VRVgE2iGzmp60xwX_WxyaSEtbOr_CKOZnhvHf3919Deg1QsICpoofmuS9rP0VdkArGefkWXX26zh7mlx9-IZkUE=s1600-w1000",
        "rating": 5,
        "type": "Burgers"
    },
    {
        "address": "36470 Moravian Dr, Clinton Twp, MI 48035, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Coming Soon! \ndescription: Coming Soon! \n",
        "id": 42,
        "lat": 42.5641822,
        "lng": -82.9522094,
        "name": "Sajos of Clinton",
        "num_of_reviews": 0,
        "phone_number": "(586) 792-7256",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj424pRZNesss5ED2nKGWL-pTmzqd-uaMVf1iHpaUP4AiusXVWYtuvKqv0w1tVy6cNdfER6pL5WbKAo0ucpMIRwDXKwpw6IHDBiE=s1600-w640",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "17460 Hall Road The Mall at, Partridge Creek Blvd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Coming Soon! \ndescription: Coming Soon! \n",
        "id": 43,
        "lat": 42.6256007,
        "lng": -82.9441951,
        "name": "Bar Louie - The Mall at Partridge Creek",
        "num_of_reviews": 0,
        "phone_number": "(586) 464-3000",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43VfApP1VaFTrW450Y56Z3g9qcg6iLu6RipitsVgCDZIPAxV3bJQV1lQsYXBJN6aTLVElN3H382HovbEXjAh7u36xvE6RgSntY=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "32976 Gratiot Ave, Roseville, MI 48066, USA",
        "capacity": 20,
        "city": "Roseville",
        "description": "Coming Soon! \ndescription: Coming Soon! \n",
        "id": 44,
        "lat": 42.5393342,
        "lng": -82.9085873,
        "name": "Hooters",
        "num_of_reviews": 0,
        "phone_number": "(586) 415-9870",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj41tjUekPmXjXB3uDMmmS4BRKnL6hJPUUddR2r6MIwMsPhWUyoDSwHQOdKDMClxo6vPxD0MBwykS9kDFT7xcB-9XCV1VMqz8rgU=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "3720 Rochester Rd, Troy, MI 48083, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Da Francesco's Ristorante and Bar serves classic recipes in a family friendly location that includes a full bar with a beautiful selection of domestic and Italian imported wines. Guests can stop in for lunch and dinner and enjoy the rustic decor paired with homemade dishes that have been passed down through the Belcastro family. We offer a kids and gluten-free menu so everyone can find a favorite on the menu. We offer plenty of bread and soup or salad before starting their meal, or visitors can start with the appetizers, which include Arancini di Riso, Mamma's Meatballs, Fried Calamari, Sausage and Hot Peppers and more. The menu features specialties like the Ravioli con Sugo, Eggplant or Pollo Parmigiana and Gnocci! We also offer plenty of meat and fish choices, including steak alla Francesco, Domenics Filet Mignon, Perch Lemone and Parmigiana Pickerel. Lastly, to end your night just right, finish it off with Mamma Sue's Homemade Tiramisu and a fresh Italian Cappuccino!\ndescription: Da Francesco's Ristorante and Bar serves classic recipes in a family friendly location that includes a full bar with a beautiful selection of domestic and Italian imported wines. Guests can stop in for lunch and dinner and enjoy the rustic decor paired with homemade dishes that have been passed down through the Belcastro family. We offer a kids and gluten-free menu so everyone can find a favorite on the menu. We offer plenty of bread and soup or salad before starting their meal, or visitors can start with the appetizers, which include Arancini di Riso, Mamma's Meatballs, Fried Calamari, Sausage and Hot Peppers and more. The menu features specialties like the Ravioli con Sugo, Eggplant or Pollo Parmigiana and Gnocci! We also offer plenty of meat and fish choices, including steak alla Francesco, Domenics Filet Mignon, Perch Lemone and Parmigiana Pickerel. Lastly, to end your night just right, finish it off with Mamma Sue's Homemade Tiramisu and a fresh Italian Cappuccino!\n",
        "id": 45,
        "lat": 42.5727111,
        "lng": -83.1272448,
        "name": "La Marsa Troy",
        "num_of_reviews": 0,
        "phone_number": "(248) 524-0300",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40DNjObilDp-WBjxolif-oECY3D-kRihjuGMQrGp44r3v1TK60RMNdLXLljFRMaHOGZ5ng6kI5qu2ElVo0ckyDADIqL-QDhDi8=s1600-w1000",
        "rating": 5,
        "type": "Mediterranean"
    },
    {
        "address": "31917 Utica Rd, Fraser, MI 48026, USA",
        "capacity": 20,
        "city": "Fraser",
        "description": "Located at the intersection of Big Beaver Road and Coolidge Highway across from the Somerset Collection shopping center, Ocean Prime is a nationally acclaimed, modern American restaurant & lounge from the award-winning Cameron Mitchell Restaurants. Stunning settings, an impressive menu of seafood & steaks, and genuine hospitality make Ocean Prime the ideal place to socialize, talk business, celebrate & indulge. Reservations are recommended.\ndescription: Located at the intersection of Big Beaver Road and Coolidge Highway across from the Somerset Collection shopping center, Ocean Prime is a nationally acclaimed, modern American restaurant & lounge from the award-winning Cameron Mitchell Restaurants. Stunning settings, an impressive menu of seafood & steaks, and genuine hospitality make Ocean Prime the ideal place to socialize, talk business, celebrate & indulge. Reservations are recommended.\n\nOcean Prime strives to provide an elegant, fine dining atmosphere. Our associates’ priority is to ensure your experience is memorable. We ask that our guests choose attire that is both polished and suited to our restaurant.\nTHANK YOU FOR NOT WEARING:\nClothing emitting excessive marijuana odor\nExcessively revealing clothing or exposed undergarments\nClothing with offensive language or graphics\nAdmittance to Ocean Prime is at the discretion of management who reserves the right to refuse service to patrons who are inappropriately dressed.\n",
        "id": 46,
        "lat": 42.5311533,
        "lng": -82.94926079999999,
        "name": "Ram's Horn Fraser",
        "num_of_reviews": 0,
        "phone_number": "(586) 296-1744",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj428WlK3LhqGdZjWNk3Hp3Eo84QY0YWFAjb9GeeVZpXLdm2ze5-qNcrx2GnBde0EuXdBZniwVRju6JRarI96dXzkp9gGJaMokkc=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "49521 Van Dyke Ave, Shelby Township, MI 48317, USA",
        "capacity": 20,
        "city": "Shelby Twp",
        "description": "Cooper’s Hawk Winery & Restaurant combines modern, casual dining with award-winning, handcrafted wines. Our menu features fresh contemporary-American fare infused with flavors from around the world. From appetizers to desserts, each dish on our menu is listed with a bin number to help guide you to your selection’s perfect wine match. In addition to dining, Cooper’s Hawk offers a full-service bar, private party spaces, and Napa-style tasting room with specialty gift store, where guests can enjoy sipping and sampling wines in a traditional winery setting. Sourcing the highest quality grapes from the best vineyards around the world has earned Cooper’s Hawk a growing list of more than 200 wine awards.\ndescription: Cooper’s Hawk Winery & Restaurant combines modern, casual dining with award-winning, handcrafted wines. Our menu features fresh contemporary-American fare infused with flavors from around the world. From appetizers to desserts, each dish on our menu is listed with a bin number to help guide you to your selection’s perfect wine match. In addition to dining, Cooper’s Hawk offers a full-service bar, private party spaces, and Napa-style tasting room with specialty gift store, where guests can enjoy sipping and sampling wines in a traditional winery setting. Sourcing the highest quality grapes from the best vineyards around the world has earned Cooper’s Hawk a growing list of more than 200 wine awards.\n",
        "id": 47,
        "lat": 42.65900389999999,
        "lng": -83.0343753,
        "name": "Da Francesco's Ristorante & Bar",
        "num_of_reviews": 0,
        "phone_number": "(586) 731-7544",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40H_RF8ck6WQh8pcCoIqAwW9Hjxw_cnjJ2jCqAS7UOLEGP2yp0Ewjo2ppNQ03crBhHuLt3fqZKkjlR3JWZxaIPc193M92VGBPs=s1600-w1000",
        "rating": 5,
        "type": "Italian"
    },
    {
        "address": "2915 Coolidge Hwy, Troy, MI 48084, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Time counts at BJ’s Restaurant & Brewhouse. Since our humble beginnings back in 1978, we’ve continued to refine our brewhouse experience to make BJ’s a place where you can make the most of any meal. We want BJ’s to be a place where the moment you leave is the moment you plan on coming back. We pride ourselves in our craft and attention to detail. Our guests come here for our award-winning handcrafted beer. They come here for the Southern California twist we’ve put on the Chicago-style deep dish pizza. And they come here for our Pizookies®, our world-renowned dessert. But above all we know people come here to make their good times better. So in many ways we haven’t just crafted a brand, but a mindset. And our guests are the reason for this. And it’s because of them we’re continually striving to make sure every moment they choose to spend with us counts. Welcome to BJ’s, a restaurant with a Brewhouse soul.\ndescription: Time counts at BJ’s Restaurant & Brewhouse. Since our humble beginnings back in 1978, we’ve continued to refine our brewhouse experience to make BJ’s a place where you can make the most of any meal. We want BJ’s to be a place where the moment you leave is the moment you plan on coming back. We pride ourselves in our craft and attention to detail. Our guests come here for our award-winning handcrafted beer. They come here for the Southern California twist we’ve put on the Chicago-style deep dish pizza. And they come here for our Pizookies®, our world-renowned dessert. But above all we know people come here to make their good times better. So in many ways we haven’t just crafted a brand, but a mindset. And our guests are the reason for this. And it’s because of them we’re continually striving to make sure every moment they choose to spend with us counts. Welcome to BJ’s, a restaurant with a Brewhouse soul.\n",
        "id": 48,
        "lat": 42.56048969999999,
        "lng": -83.1874242,
        "name": "Ocean Prime Detroit",
        "num_of_reviews": 0,
        "phone_number": "(248) 458-0500",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40WT2U8RwvxAVn8WSB6sXsI96y646UnasYnR9Mu_ewyhRVZE2s6VNzNcg-G8JeVdalW1l8dLabxQMJPpN86IekusTgKUhzffOc=s1600-w845",
        "rating": 5,
        "type": "Seafood"
    },
    {
        "address": "17440 Hall Rd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Brio Partridge Creek is a premier Tuscan-inspired restaurant destination serving authentic, northern Italian cuisine, luxury wines & cocktails—our specialties include premium quality steaks, chops, seafood, made-to-order pasta and flatbreads prepared in an authentic Italian wood-burning oven.\ndescription: Brio Partridge Creek is a premier Tuscan-inspired restaurant destination serving authentic, northern Italian cuisine, luxury wines & cocktails—our specialties include premium quality steaks, chops, seafood, made-to-order pasta and flatbreads prepared in an authentic Italian wood-burning oven.\n",
        "id": 49,
        "lat": 42.62592609999999,
        "lng": -82.9444754,
        "name": "Cooper’s Hawk Winery & Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(586) 464-9463",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40mFjXgA0In8-1M852xXU9UXzoh5rtCKAhzRIK5vVWYcSPJKvMpuxbGev63zZ9GoAAxMpZJcn_LhZmBlVZanrWIPEXcNJoG42U=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "151 E Big Beaver Rd, Troy, MI 48083, USA",
        "capacity": 20,
        "city": "Troy",
        "description": "Voted #1 Fish & Chips and Best Seafood by Macomb Daily.\ndescription: Voted #1 Fish & Chips and Best Seafood by Macomb Daily.\n\n\n\nOur kitchen is filled with talented Chefs who work tirelessly on plate presentation and quality standards. The process begins with our chef hand cutting large atlantic cod loins, then battering and cooking the cod fresh for each order.\n",
        "id": 50,
        "lat": 42.56292550000001,
        "lng": -83.1447013,
        "name": "Cooper's Hawk Winery & Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(248) 781-8811",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42Rg4E7F4reWH4CAgwWMD4_y4tfd-5x5gwaI-FJCX8-Hp2KzbzcI0TUjS_xqosE3Z59_x49_AMKfHhRrox0nSD4L0n2D6ab6HM=s1600-w1000",
        "rating": 5,
        "type": "Contemporary American"
    },
    {
        "address": "14455 Lakeside Cir, Sterling Heights, MI 48313, USA",
        "capacity": 20,
        "city": "Sterling Heights",
        "description": "Harbor House features the freshest seafood and all you can eat options daily. Come on in and enjoy a drink from our full bar while enjoying the freshest seafood available. \ndescription: Harbor House features the freshest seafood and all you can eat options daily. Come on in and enjoy a drink from our full bar while enjoying the freshest seafood available. \n",
        "id": 51,
        "lat": 42.6263892,
        "lng": -82.9839666,
        "name": "BJ's Restaurant & Brewhouse",
        "num_of_reviews": 0,
        "phone_number": "(586) 519-6250",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj41y4DV1c70bcpRsLlNmV53aC4fb3RlaGLw744FxKbykC_TGzAbJ1IMeZqUkUuRrhITFjDCNvJq-2Cmn6HGQVug8WtftjzQ_hTA=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "19470 Haggerty Rd, Livonia, MI 48152, USA",
        "capacity": 20,
        "city": "Livonia",
        "description": "Bath City Bistro provides a unique dining and diversion experience for the Metro Detroit area, centered on the Belgian sport of Feather Bowling. This fun activity is coupled with a menu concentrating on steaks, pizza, the obligatory mussels, and a variety of foods to attract patrons of all palates. And of course, your favorite adult beverages.\ndescription: Bath City Bistro provides a unique dining and diversion experience for the Metro Detroit area, centered on the Belgian sport of Feather Bowling. This fun activity is coupled with a menu concentrating on steaks, pizza, the obligatory mussels, and a variety of foods to attract patrons of all palates. And of course, your favorite adult beverages.\n\nOur warm and attractive décor is intended as an unrivaled blend of the turn of the century architecture of Mt. Clemens, featuring photographs that highlight its rich heritage when it was known as “Bath City, U.S.A” for its mineral bath houses. The original brick and wood accents of the building have been restored to convey a sense of warmth and friendliness.\n\nBath City Bistro features three lanes of Belgian Feather Bowling, a Belgian sport that could be described as a cross between bocci ball and shuffleboard.\n",
        "id": 52,
        "lat": 42.4278121,
        "lng": -83.4324431,
        "name": "BJ's Restaurant & Brewhouse",
        "num_of_reviews": 0,
        "phone_number": "(734) 357-8530",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42nZyZMTL828CY4yGufI70PXoaEv-6cxdOnY9A2d023WeI-bQPENAczSgHrFCejt_A4DGb7Z7iBKQNUvYuSvsqD6S1Xq4VXLyc=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "17430 Hall Rd, Sterling Heights, MI 48038, USA",
        "capacity": 20,
        "city": "Sterling Heights",
        "description": "BurgerFin's unique fusion of Sliders and Sushi offers something for everyone in an upbeat, casual atmosphere. From game time to family time, we're your regular hang out to dine, drink, watch and relax. \ndescription: BurgerFin's unique fusion of Sliders and Sushi offers something for everyone in an upbeat, casual atmosphere. From game time to family time, we're your regular hang out to dine, drink, watch and relax. \n",
        "id": 53,
        "lat": 42.62655900000001,
        "lng": -82.9456857,
        "name": "Brio Italian Grille",
        "num_of_reviews": 0,
        "phone_number": "(586) 263-7310",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj405vNeu-fXkUhei91QxjhTSSoD7h61NlBjE_j9zPBgtWhhQVh_abN6Y61gZ9hhboTWTGZvY19urF7P7Pt1ttQCApprKg-GUGNI=s1600-w1000",
        "rating": 5,
        "type": "Italian"
    },
    {
        "address": "36470 Jefferson Ave, Harrison Twp, MI 48045, USA",
        "capacity": 20,
        "city": "Harrison Twp",
        "description": "We are an Asian & Chinese restaurant offering dine-in, takeout, to-go, delivery, and catering. Make a reservation online to dine in. Order Asian and Chinese food delivery, takeout, and catering online or through the P.F. Chang's mobile app. Let us cater the perfect feast for you - corporate office catering menus are also available. P.F. Chang’s offers a variety of signature Asian, Thai, Korean, Japanese, Mongolian, and Chinese food dishes including Chicken Lettuce Wraps, Chicken Pad Thai, Signature Lo Mein, Fried Rice, Mongolian Beef, Chang's Spicy Chicken, and Pork and Shrimp Dumplings. Order online for sushi delivery and takeout. Many gluten-free and vegetarian menu items are available. Try our seasonal cocktails and seasonal menu items.\ndescription: We are an Asian & Chinese restaurant offering dine-in, takeout, to-go, delivery, and catering. Make a reservation online to dine in. Order Asian and Chinese food delivery, takeout, and catering online or through the P.F. Chang's mobile app. Let us cater the perfect feast for you - corporate office catering menus are also available. P.F. Chang’s offers a variety of signature Asian, Thai, Korean, Japanese, Mongolian, and Chinese food dishes including Chicken Lettuce Wraps, Chicken Pad Thai, Signature Lo Mein, Fried Rice, Mongolian Beef, Chang's Spicy Chicken, and Pork and Shrimp Dumplings. Order online for sushi delivery and takeout. Many gluten-free and vegetarian menu items are available. Try our seasonal cocktails and seasonal menu items.\n",
        "id": 54,
        "lat": 42.5661392,
        "lng": -82.8422851,
        "name": "Terry's Terrace",
        "num_of_reviews": 0,
        "phone_number": "(586) 463-2671",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43HdvlU2_NX6MjFjo0zNnFAMZ9yIR7xNlNnYrRo1OFEUDnLMuZdIKcCtGyCUzAIO_L3FwMoaeaYdr15LfBjEsYfxzPBrxWI4Vo=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "34250 Groesbeck Hwy, Clinton Twp, MI 48035, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\ndescription: Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\n",
        "id": 55,
        "lat": 42.5486179,
        "lng": -82.9272337,
        "name": "Harbor House Restaurant",
        "num_of_reviews": 0,
        "phone_number": "(586) 791-6070",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj41_8xVMytPEGhNtGv7sKn6leP_JXY58bf_nFuHEXgXIxVcBrsEpzZHVeLa6PJ6HtL8P6DkqjY6qjC-ju5B_zH0-9pSjvMSOn7Q=s1600-w1000",
        "rating": 5,
        "type": "Seafood"
    },
    {
        "address": "75 Macomb Pl, Mt Clemens, MI 48043, USA",
        "capacity": 20,
        "city": "Mt Clemens",
        "description": "Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\ndescription: Since 1982, Buffalo Wild Wings® (or B-Dubs® as our friends call us) has been the ultimate place to watch the game, have a cold beer and eat some great food. At Buffalo Wild Wings, you can always feel comfortable pulling some tables together with your friends and staying as long as you want.\n",
        "id": 56,
        "lat": 42.5985573,
        "lng": -82.87908829999999,
        "name": "Bath City Bistro",
        "num_of_reviews": 0,
        "phone_number": "(586) 469-0917",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42L2YZmKAwFG0A3mdEaojpD2i4-oZOMYfZQ4ZwlWyARHpDUXthvHWKEWhb5Tq8Ghi85x1GGkhxvWPs9w9MU2f6VbHXMi_gNikE=s1600-w960",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "17380 Hall Rd, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Rendezvous Restaurant\ndescription: Rendezvous Restaurant\n36217 S Gratiot Ave\nClinton Twp MI 48035\n586-913-7701\n",
        "id": 57,
        "lat": 42.625928,
        "lng": -82.9475927,
        "name": "BurgerFin Partridge Creek",
        "num_of_reviews": 0,
        "phone_number": "(586) 422-0085",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40mvmtwpcBHF_jXO19RGpB6pZAJ06cKWnmVT_cMFfbiHHmhS1gthA7IoZICcEkzWf0rME5ywJJHhC1xgt2HN5PvgZY9t7F_3tA=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "17390 Hall Rd Unit R-103, Clinton Twp, MI 48038, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "Our authentic BBQ starts in a live-wood smoker stoked with genuine hickory logs. Our pitmasters hand-rub the meats with a custom blend of spices and cook for hours to extract the natural flavors. We source the highest quality meats and trim them up like we’re in a competition and hand-rub them with the freshest seasonings available to create mouthwatering experiences! In addition to our BBQ and grilled meats, our menu features a selection of salads, sandwiches, side items, and made-from-scratch desserts.\ndescription: Our authentic BBQ starts in a live-wood smoker stoked with genuine hickory logs. Our pitmasters hand-rub the meats with a custom blend of spices and cook for hours to extract the natural flavors. We source the highest quality meats and trim them up like we’re in a competition and hand-rub them with the freshest seasonings available to create mouthwatering experiences! In addition to our BBQ and grilled meats, our menu features a selection of salads, sandwiches, side items, and made-from-scratch desserts.\n",
        "id": 58,
        "lat": 42.6265339,
        "lng": -82.94633520000001,
        "name": "P.F. Chang's",
        "num_of_reviews": 0,
        "phone_number": "(586) 263-0860",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj416DB2bmCiD0rk3kXZO9FCZsxJ85jLYWMi-UhazH08pzXMCPc-8MnTOsi6f2KK3qmFJxIrWQMROoxGKVXnS4fatRBY4-2Rf5UM=s1600-w1000",
        "rating": 5,
        "type": "Asian"
    },
    {
        "address": "48 Market St, Mt Clemens, MI 48043, USA",
        "capacity": 20,
        "city": "Mt Clemens",
        "description": "",
        "id": 59,
        "lat": 42.5990802,
        "lng": -82.8757133,
        "name": "Buffalo Wild Wings",
        "num_of_reviews": 0,
        "phone_number": "(586) 469-0725",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj42LpwLbZZ92fznGad75OheqafbSwO40oab3KmWCnMQiGyy8XDrg2_i2pNxm7WrTBvhYRLm79O-2-sLcXbhe9O2WUvaVHVXyHf0=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "15745 15 Mile Rd, Clinton Twp, MI 48035, USA",
        "capacity": 20,
        "city": "Clinton Twp",
        "description": "",
        "id": 60,
        "lat": 42.5537207,
        "lng": -82.9636486,
        "name": "Buffalo Wild Wings",
        "num_of_reviews": 0,
        "phone_number": "(586) 293-9500",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj43qLVZOTREXeJBndKc4dituc71bZv8s2u-RPmMA2AIrILNU4sGirAIUPsYykmljp4EOLys2i0ROenQW6IXW3F4QVBY6hIHEpCQ=s1600-w1000",
        "rating": 5,
        "type": "American"
    },
    {
        "address": "13411 15 Mile Rd, Sterling Heights, MI 48312, USA",
        "capacity": 20,
        "city": "Sterling Heights",
        "description": "",
        "id": 61,
        "lat": 42.5534819,
        "lng": -82.9905473,
        "name": "Cloverleaf Pizza",
        "num_of_reviews": 0,
        "phone_number": "(586) 264-9700",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40vKy7rEfSAorKuuJ6_4zWzFpP5ispy3erfVlKxXZntN5h2b_Ir2Td-BZT82lgkaSTVPBL3GXvh0gf5OpE1XccwxZPOpi7w7fw=s1600-w1000",
        "rating": 5,
        "type": "1 review"
    },
    {
        "address": "20300 E Thirteen Mile Rd, Roseville, MI 48066, USA",
        "capacity": 20,
        "city": "Roseville",
        "description": "Red Lobster is the world's largest and most loved seafood restaurant company, offering high quality, freshly-prepared seafood, sourced in a way that is traceable, sustainable and responsible. We offer lunch and dinner daily, featuring classics like our Ultimate Feast®, Garlic Shrimp Scampi and Parrot Isle Jumbo Coconut Shrimp, and feature limited time flavors and preparations during events like Lobsterfest®, Crabfest® and Endless Shrimp®. And, who can resist our famous warm and cheesy Cheddar Bay Biscuits®? To learn more visit www.redlobster.com.\ndescription: Red Lobster is the world's largest and most loved seafood restaurant company, offering high quality, freshly-prepared seafood, sourced in a way that is traceable, sustainable and responsible. We offer lunch and dinner daily, featuring classics like our Ultimate Feast®, Garlic Shrimp Scampi and Parrot Isle Jumbo Coconut Shrimp, and feature limited time flavors and preparations during events like Lobsterfest®, Crabfest® and Endless Shrimp®. And, who can resist our famous warm and cheesy Cheddar Bay Biscuits®? To learn more visit www.redlobster.com.\n",
        "id": 62,
        "lat": 42.524419,
        "lng": -82.9143155,
        "name": "Famous Dave's Bar-B-Que",
        "num_of_reviews": 0,
        "phone_number": "(586) 293-2900",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj40ss9AKCUCEbvQeLpqj1zuD4rjE0w_GIDTrcju5ohKCleMKZOTvCadfUaj4ZlcmPJBVU76mHOsx_Z3PXXp8-snnzlTzKBhWaEo=s1600-w315",
        "rating": 5,
        "type": "Barbecue"
    },
    {
        "address": "LAKESIDE MALL, 13800 Hall Rd, Sterling Heights, MI 48313, USA",
        "capacity": 20,
        "city": "Sterling Heights",
        "description": "",
        "id": 63,
        "lat": 42.626157,
        "lng": -82.9898,
        "name": "Red Lobster",
        "num_of_reviews": 0,
        "phone_number": "(586) 247-6250",
        "preview_image": "https://lh3.googleusercontent.com/places/AJDFj4013V6SNa_ydtWcqIxUhP-Y6RM7IEjJE7yyd28e9WNEyuU48p3W_WwC5EnCEFrkLBy_G1zW6TOHewW-mTjkuuQGc9HpP08Qbl8=s1600-w1000",
        "rating": 5,
        "type": "Seafood"
    }
]

